apiVersion: v1
kind: ConfigMap
metadata:
  name: kube5gnfvo-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUlBVXo3eWtPRGtUTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU5qQXhNakV3TkRJek5EQmFGdzB6TmpBeE1Ua3dOREl6TkRCYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNSU9ZVmtyWmRmencvUjJRRmdBWHlWWHZ5WHorTnhQZ21KT09mQzFuNVJPcFNVT3dGdWwKSlBncjF2aWREZFFMUnMzWm9NMHl0eTV6aERDclN4Tms0UllwYjR4VXZVRWFUOFRXZ0N5ZFdhS3R3b0JFTldWOAo2VnlBemZNeVVwaWZaeVNzK29nd1AreEErYVlvWHp4SHNpUHk0Mzh6YURscUJpb0x5MVo3djNraXJmU1VRUU1KCmpPeG0vRUVVeUpwRGpEaGg1aE9LdVVGcU0xeVI1QnM0RDR5dnhkVWI1VWpsT0RTSS9CWWx4RWs5WUhGMEZobmMKcXJ2QktiNXJhZ1AwbGsxUCtUWnYrQ1hEZk12Z2NRZkVsZHVFTFJieHp3NDZVVmtOOVdrNXRyMzdSUjM4dm4xYQpIakdSc0hYM3Fjek9laFJBSlRSOXBTRDN0bTM4a1B2SHhMOENBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGSXNRCmFTRHZGOGJPc25Rc0xTUnNWRGl4c2NxUE1COEdBMVVkSXdRWU1CYUFGSXNRYVNEdkY4Yk9zblFzTFNSc1ZEaXgKc2NxUE1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFUY0FkT3pQVWdISG95VAo5VXN6UzhXS1FDcmJZSFF4YzhlT2ZuZnpPeFNMeTBLMDZjek9qd2ZOSTZMMURqR1MyaUd0QmpYcmNaVnh4ajNICkFuNy8rZ01ucUFmTU1vR2dXeVZwTm9wTGJTamZZTjNQQlFFZk5BcWZLN2ljTDc4WWphU3NFRkp1aUp2N2wveWEKTlYrd0NhN0duOWdpdEMvZmJhTG16YnpnNE4rc0F4WkNPNjhCa0l6eVUzamh0emFnU2R5bTFSODlTWXZMVEhpbwp2OXJkU0hoc2g3SEFab0RYN3VNaGJBZkcyeXNKRExBbTRieXhZeXpLMjltTzR1dDVvVTBWcUp3K3JRWkh0bmFZClV6S0JXWDFYMUZ0VXE5UDBJNjlQNzY3NVl2ZHNYY256NVBBTmdaOWs1U3NZYUxxTWVCbUUvR3ZRVHZhdlhGcUMKQ0FZWGhkdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://kubernetes.default.svc:443
      name: microk8s-cluster
    contexts:
    - context:
        cluster: microk8s-cluster
        user: admin
      name: microk8s
    current-context: microk8s
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        username: admin
        password: U2Q3eFdLeUkzaVFhb2hJNXYyc3FsUFZnUmFtY1pGYTRWcHdXVVc0Tlh0dz0K